version: '3.8'

services:
    phpmyadmin:
        container_name: myadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        network_mode: jarvis-network
        ports:
            - '9000:80'
        image: phpmyadmin/phpmyadmin
        volumes:
            - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
